### ISSUE TITLE
TypeError: opts.connector is not a function

### ISSUE THREAD

**Issue by zeeshanalisyed** [Emallates/enoa-client#3]
I was including two objects of enoa-client in the application which was running single process that gave me below given error.

```
/home/usr/rep/server/node_modules/enoa-client/lib/enoaclient.js:17
  opts.connector = new opts.connector(opts);
                   ^

TypeError: opts.connector is not a function
    at new enoaClient (/home/usr/rep/server/node_modules/enoa-client/lib/enoaclient.js:17:20)
    at Object.<anonymous> (/home/usr/rep/server/dist/controllers/index.js:1:1359)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/home/usr/rep/server/dist/r/index.js:1:154)
    at /home/usr/rep/server/dist/server.js:1:847
    at nextTask (/home/usr/rep/server/node_modules/async/dist/async.js:6627:18)
    at /home/usr/rep/server/node_modules/async/dist/async.js:6621:17
    at /home/usr/rep/server/node_modules/async/dist/async.js:339:31
    at /home/usr/rep/server/node_modules/async/dist/async.js:840:20
    at /home/usr/rep/server/dist/server.js:1:811
    at nextTask (/home/usr/rep/server/node_modules/async/dist/async.js:6627:18)
    at /home/usr/rep/server/node_modules/async/dist/async.js:6621:17
    at /home/usr/rep/server/node_modules/async/dist/async.js:339:31
    at /home/usr/rep/server/node_modules/async/dist/async.js:840:20
    at /home/usr/rep/server/node_modules/waterline/lib/waterline.js:211:7
    at /home/usr/rep/server/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /home/usr/rep/server/node_modules/waterline/node_modules/async/lib/async.js:269:32
    at /home/usr/rep/server/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /home/usr/rep/server/node_modules/waterline/lib/waterline/query/index.js:69:7
    at module.exports [as migrateSafe] (/home/usr/rep/server/node_modules/waterline/lib/waterline/adapter/sync/strategies/safe.js:14:3)
    at Query.sync (/home/usr/rep/server/node_modules/waterline/lib/waterline/query/index.js:67:37)
    at /home/usr/rep/server/node_modules/waterline/lib/waterline.js:280:16
    at /home/usr/rep/server/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at Immediate.iterate [as _onImmediate] (/home/usr/rep/server/node_modules/waterline/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by nomi-ramzan** [comment]
Please send your configuration code as well.

**Comment by zeeshanalisyed** [comment]
```
var conf = {
   appId:'app_id', apiKey:'apiKey'  
   , collections:{      
       zlog:{
           appId:'_id', apiKey:'_key',
           adapter:require('zlogjs-adapter'), 
           host:'localhost', port:'9000' ,
           mode:"central"
       }
   }
};

```

**Comment by nomi-ramzan** [comment]
Thank you. This issue is resolved now. Please reopen this issue if you still have this problem.
